# Generated by Django 5.2.1 on 2025-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='monthly_mortgage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly mortgage payment (0 if no mortgage)', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rental', 'Rental Property'), ('owner_occupied', 'Owner Occupied'), ('owned_outright', 'Owned Outright')], default='rental', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly rental income (0 if not rented)', max_digits=10),
        ),
    ]
