# Generated by Django 5.2.1 on 2025-07-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_customuser_is_verified_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email_constraint'),
        ),
    ]
