# Generated by Django 5.2.1 on 2025-07-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_monthly_mortgage_property_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_mortgage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
