# Generated by Django 5.2.1 on 2025-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original purchase price', max_digits=12),
            preserve_default=False,
        ),
    ]
